language: php

# Which PHP versions we want to test
php:
  - 7.0
  - 5.6

# Which versions are allowed to fail
matrix:
  allow_failures:
    - php: 5.6

# Which branches we want to test
branches:
  only:
    - master
    - develop
    - /^release-.*$/

before_install:
  - composer selfupdate

install:
  - composer install

after_script:
  - ./vendor/bin/codacycoverage clover
